export const CODE_FILES: { name: string; lang: string; content: string }[] = [
  {
    name: "src/index.ts",
    lang: "typescript",
    content: `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { registerWeatherTools } from "./tools/weather.js";

const server = new McpServer({
  name: "weather-mcp-server",
  version: "1.0.0",
});

registerWeatherTools(server);

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Weather MCP server running on stdio");
}

main().catch(console.error);`,
  },
  {
    name: "src/tools/weather.ts",
    lang: "typescript",
    content: `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { GetCurrentWeatherSchema, GetForecastSchema } from "../schemas/weather.js";
import { fetchCurrentWeather, fetchForecast } from "../api/weather.js";

export function registerWeatherTools(server: McpServer) {
  server.tool(
    "get_current_weather",
    "Get the current weather for a city or coordinates.",
    GetCurrentWeatherSchema.shape,
    async ({ location, units }) => {
      const data = await fetchCurrentWeather(location, units ?? "metric");
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      };
    }
  );

  server.tool(
    "get_forecast",
    "Get a 5-day weather forecast for a location.",
    GetForecastSchema.shape,
    async ({ location, days, units }) => {
      const forecast = await fetchForecast(location, days ?? 5, units ?? "metric");
      return {
        content: [{ type: "text", text: JSON.stringify(forecast, null, 2) }],
      };
    }
  );
}`,
  },
  {
    name: "src/schemas/weather.ts",
    lang: "typescript",
    content: `import { z } from "zod";

export const GetCurrentWeatherSchema = z.object({
  location: z
    .string()
    .min(1)
    .max(200)
    .describe("City name or 'lat,lon' coordinates, e.g. 'London' or '51.5,-0.1'"),
  units: z
    .enum(["metric", "imperial", "standard"])
    .optional()
    .describe("Unit system — metric (°C), imperial (°F), or standard (K)"),
});

export const GetForecastSchema = z.object({
  location: z
    .string()
    .min(1)
    .max(200)
    .describe("City name or 'lat,lon' coordinates"),
  days: z
    .number()
    .int()
    .min(1)
    .max(16)
    .optional()
    .describe("Number of days to forecast (1–16, default 5)"),
  units: z
    .enum(["metric", "imperial", "standard"])
    .optional()
    .describe("Unit system"),
});

export type GetCurrentWeatherInput = z.infer<typeof GetCurrentWeatherSchema>;
export type GetForecastInput = z.infer<typeof GetForecastSchema>;`,
  },
  {
    name: "package.json",
    lang: "json",
    content: `{
  "name": "weather-mcp-server",
  "version": "1.0.0",
  "type": "module",
  "description": "MCP server for real-time weather data — generated by FloMCP",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/index.js",
    "dev": "tsx src/index.ts"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "typescript": "^5.3.0",
    "tsx": "^4.7.0",
    "@types/node": "^20.0.0"
  }
}`,
  },
  {
    name: "README.md",
    lang: "markdown",
    content: `# Weather MCP Server

Generated by FloMCP — production-ready MCP server.

## Setup

\`\`\`bash
npm install
npm run build
\`\`\`

## Configuration

Add to your Claude Desktop \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "weather": {
      "command": "node",
      "args": ["/absolute/path/to/dist/index.js"],
      "env": {
        "OPENWEATHER_API_KEY": "your_api_key_here"
      }
    }
  }
}
\`\`\`

## Available Tools

- **get_current_weather** — Current weather for any city or coordinates
- **get_forecast** — 5-day forecast with configurable units

## Security

- Input validated with Zod schemas
- No hardcoded secrets — all config via environment variables
- SSRF-safe: only calls the OpenWeatherMap API domain`,
  },
];
