export const CODE_FILES: { name: string; lang: string; content: string }[] = [
  {
    name: "src/index.ts",
    lang: "typescript",
    content: `#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const server = new McpServer(
  { name: "regex-lab", version: "1.0.0" },
  { capabilities: { tools: {}, prompts: {}, resources: {} } }
);

// ── ReDoS protection ────────────────────────────────────────────────────────
function isLikelyReDoS(pattern: string): boolean {
  if (/\\([^)]*[+*][^)]*\\)[+*]/.test(pattern)) return true;
  if (/\\([^)]*\\|[^)]*\\)[+*]/.test(pattern)) return true;
  return false;
}

// ── Tool: test_regex ─────────────────────────────────────────────────────────
server.tool(
  "test_regex",
  "Test a regular expression pattern against text and extract all matches, capture groups, and named groups",
  {
    pattern: z.string().trim().min(1).max(2000).describe("Regular expression pattern"),
    text: z.string().max(10_000).describe("Input text to test against"),
    flags: z.string().trim().regex(/^[gimsuvyd]*$/).optional().default("").describe("Regex flags (g, i, m, s, u)"),
  },
  async ({ pattern, text, flags }) => {
    if (isLikelyReDoS(pattern)) {
      return { content: [{ type: "text" as const, text: "Pattern rejected: ReDoS risk detected." }], isError: true };
    }
    try {
      if (flags.includes("g") || flags.includes("y")) {
        const all = [...text.matchAll(new RegExp(pattern, flags))];
        return { content: [{ type: "text" as const, text: JSON.stringify({ matched: all.length > 0, totalMatches: all.length, matches: all.map(m => ({ fullMatch: m[0], index: m.index, captures: m.slice(1) })) }, null, 2) }] };
      }
      const m = new RegExp(pattern, flags).exec(text);
      if (!m) return { content: [{ type: "text" as const, text: JSON.stringify({ matched: false, pattern, text }) }] };
      return { content: [{ type: "text" as const, text: JSON.stringify({ matched: true, fullMatch: m[0], index: m.index, captures: m.slice(1), namedGroups: m.groups ?? null }, null, 2) }] };
    } catch (e) {
      return { content: [{ type: "text" as const, text: e instanceof Error ? e.message : "Regex error" }], isError: true };
    }
  }
);

// ── Tool: explain_regex ───────────────────────────────────────────────────────
server.tool(
  "explain_regex",
  "Get a human-readable explanation of what a regular expression pattern does",
  { pattern: z.string().trim().min(1).max(1000).describe("Pattern to explain") },
  async ({ pattern }) => {
    try {
      new RegExp(pattern);
      const parts: string[] = [];
      if (pattern.includes("^")) parts.push("^ = Start of string");
      if (pattern.includes("$")) parts.push("$ = End of string");
      if (pattern.includes("\\d")) parts.push("\\d = Any digit (0–9)");
      if (pattern.includes("\\w")) parts.push("\\w = Word character (a-z, A-Z, 0-9, _)");
      if (pattern.includes("\\s")) parts.push("\\s = Whitespace character");
      if (pattern.includes("*")) parts.push("* = Zero or more times");
      if (pattern.includes("+")) parts.push("+ = One or more times");
      if (pattern.includes("?")) parts.push("? = Optional (zero or one)");
      if (pattern.includes("(")) parts.push("(...) = Capturing group");
      if (pattern.includes("(?:")) parts.push("(?:...) = Non-capturing group");
      if (pattern.includes("(?=")) parts.push("(?=...) = Positive lookahead");
      if (pattern.includes("(?")) parts.push("(?!...) = Negative lookahead");
      if (pattern.includes("[")) parts.push("[...] = Character class");
      if (pattern.includes("|")) parts.push("| = Alternation (OR)");
      return { content: [{ type: "text" as const, text: JSON.stringify({ pattern, components: parts.length ? parts : ["Literal characters only"] }, null, 2) }] };
    } catch (e) {
      return { content: [{ type: "text" as const, text: e instanceof Error ? e.message : "Invalid pattern" }], isError: true };
    }
  }
);

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}
main().catch(console.error);`,
  },
  {
    name: "package.json",
    lang: "json",
    content: `{
  "name": "regex-lab",
  "version": "1.0.0",
  "type": "module",
  "description": "MCP server for regex testing, explanation, and pattern library — generated by FloMCP",
  "main": "dist/index.js",
  "bin": { "regex-lab": "dist/index.js" },
  "scripts": {
    "build": "tsc",
    "start": "node dist/index.js",
    "dev": "tsx src/index.ts",
    "test": "vitest run"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.12.1",
    "zod": "^3.24.2"
  },
  "devDependencies": {
    "typescript": "^5.8.2",
    "tsx": "^4.19.3",
    "@types/node": "^22.0.0",
    "vitest": "^3.1.1"
  }
}`,
  },
  {
    name: "tsconfig.json",
    lang: "json",
    content: `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist", "tests"]
}`,
  },
  {
    name: "README.md",
    lang: "markdown",
    content: `# regex-lab MCP Server

Generated by FloMCP — production-ready MCP server.

Test, explain, and retrieve battle-tested regex patterns directly in Claude Desktop, Cursor, or any MCP-compatible AI assistant.

## Setup

\`\`\`bash
npm install
npm run build
\`\`\`

## Configuration

Add to your \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "regex-lab": {
      "command": "node",
      "args": ["/absolute/path/to/dist/index.js"]
    }
  }
}
\`\`\`

## Available Tools

- **test_regex** — Test a pattern against text, extract all matches and capture groups
- **explain_regex** — Break down what each part of a pattern does
- **get_common_pattern** — Retrieve battle-tested patterns: email, uuid, ipv4, url, jwt, semver, and 24 more
- **find_named_pattern** — Search the pattern library by keyword

## Security

- ReDoS protection — nested quantifier patterns rejected before execution
- Input validated with Zod schemas (pattern max 2000 chars, text max 10,000 chars)
- Errors sanitised — no file paths, IPs, or secrets in error output
- No hardcoded secrets — no external API calls, fully offline`,
  },
  {
    name: ".vscode/mcp.json",
    lang: "json",
    content: `// Plug regex-lab into VS Code (or Cursor) in one step.
// FloMCP auto-registers all 4 tools — no extra config needed.
{
  "servers": {
    "regex-lab": {
      "type": "stdio",
      "command": "npx",
      "args": ["tsx", "src/index.ts"]
    }
  }
}

// 4 tools, live immediately after saving this file:
//   test_regex          — run a pattern, get every match + capture group
//   explain_regex       — break down each token in plain English
//   get_common_pattern  — pull battle-tested patterns (email, uuid, jwt, …)
//   find_named_pattern  — fuzzy-search the built-in library by keyword`,
  },
];
